title: "My CTF Writeups"
description: "Documenting my journey through various CTF challenges"
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme

# Theme settings
style: dark # Perfect for CTF content!
header_pages:
  - index.md
  - platforms.md
  - categories.md
  - about.md

collections:
  posts:
    output: true
